#!/bin/sh
#SBATCH -J hop
#SBATCH -N 4
#SBATCH --tasks-per-node=48
#SBATCH --threads-per-core=1
#SBATCH --time=24:00:00
#SBATCH --partition=skylake_0096
#SBATCH --qos=skylake_0096

module purge
module load compiler/2021.3.0 intel-mkl/2021.3.0 intel-mpi/2021.3.0

export VASP=~/vasp.6.2.1_intel2021/bin/vasp_gam
conda activate venv

for t in "600K"
do
    for i in {0..9..1}
    do
        for j in {0..39..1}
        do
            dir="${t}/jump_${i}/poscar_${j}"
            echo $dir; 
            cp VASP_stuff/* ${dir}
            cd ${dir}
            pwd
            python /gpfs/data/fs71258/viktor_super/TiO2_rutile/TiO2_jumps_1/mag_init/get_magmom.py ../ $j >> INCAR
            mpirun -np 192 ${VASP}
            #next=$((j + 1))
            #cp {WAVECAR,CHGCAR} ../poscar_${next}
            cd ../../..
        done
    done
done

